# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker build -t wicochandra/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true wicochandra/react-test npm test

  deploy:
    docker:
      - image: 'cimg/base:stable'
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    environment:
      GIT_SHA: $(git rev-parse HEAD)
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run: openssl aes-256-cbc -pbkdf2 -k $encrypt_key_1 -in service-account.json.circleci.enc -out ./service-account.json -d
      - run: curl https://sdk.cloud.google.com | bash > /dev/null;
      - run: $HOME/google-cloud-sdk/bin/gcloud --quiet components update kubectl
      - run: $HOME/google-cloud-sdk/bin/gcloud --quiet auth activate-service-account --key-file service-account.json
      - run: $HOME/google-cloud-sdk/bin/gcloud --quiet config set project udemy-k8s-324201
      - run: $HOME/google-cloud-sdk/bin/gcloud --quiet config set compute/zone us-central1-c
      - run: $HOME/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials my-first-cluster-1
      - run: source $HOME/google-cloud-sdk/path.bash.inc && ./deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs: 
      - deploy:
          filters:
            branches:
              only: master
          