# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'

    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker build -t wicochandra/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true wicochandra/react-test npm test